import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import React, { Children } from 'react'
import Footer from './Footer'
import Navbar from './Navbar'

const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>E-State</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box maxWidth="1280px" m="auto">
                <header>
                    <Navbar/>
                </header>
            </Box>
            <main>
                {children}
            </main>
            <footer>
                <Footer/>
            </footer>
        </>
    )
}

export default Layout